name: On push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 2
      
      - name: Prepare information
        id: information
        run: |
          echo "time=HKT $(date '+%Y%m%d%H%M%S')" >> "${GITHUB_OUTPUT}"
          if git rev-parse --verify HEAD~1 >/dev/null 2>&1;
          then
            changes="$(git diff --stat HEAD~1 HEAD)"
          else
            changes="$(git show --stat HEAD)"
          fi
          maximumLength=3072
          if [[ ${#changes} -gt ${maximumLength} ]];
          then
            changes="${changes:0:${maximumLength}}"$'\n...'
          fi
          echo "changes<<EOF" >> "${GITHUB_OUTPUT}"
          echo "${changes}" >> "${GITHUB_OUTPUT}"
          echo "EOF" >> "${GITHUB_OUTPUT}"
        env:
          TZ: 'Asia/Hong_Kong'
      
      - name: Notify updates
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            New Push to GitHub! 
            
            - Repository: [${{ github.repository }}](${{ github.server_url }}/${{ github.repository }})
            - Branch: [${{ github.ref_name }}](${{ github.server_url }}/${{ github.repository }}/tree/${{ github.ref_name }})
            - Commit: [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
            - Workflow: [Run #${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            - Time: ${{ steps.information.outputs.time }}
            
            Changes: 
            ```
            ${{ steps.information.outputs.changes }}
            ```